version: '3.4'
x-DEFAULT-ENVIRONMENT:
  - &te-base-dir-default TE_BASE_DIR=/topicexplorer/te-production
  - &te-version-default TE_VERSION=te-1.4-SNAPSHOT

services:
  grobid:
    image: lfoppiano/grobid:0.5.6
    restart: always
    ports:
      - 8070   # API
      - 8071   # Health check
