grant all on <TE_MANAGEMENT_DB_NAME>.* to '<TE_MANAGEMENT_DB_USER>'@'localhost' IDENTIFIED BY '<TE_MANAGEMENT_DB_PASSWORD>';
grant SHOW DATABASES on *.* to '<TE_MANAGEMENT_DB_USER>'@'localhost';
grant FILE on *.* to '<TE_MANAGEMENT_DB_USER>'@'localhost';
grant CREATE USER on *.* to '<TE_MANAGEMENT_DB_USER>'@'localhost';
grant all on *.* to '<TE_MANAGEMENT_DB_USER>'@'localhost' IDENTIFIED BY '<TE_MANAGEMENT_DB_PASSWORD>';
grant GRANT OPTION on *.* to '<TE_MANAGEMENT_DB_USER>'@'localhost' IDENTIFIED BY '<TE_MANAGEMENT_DB_PASSWORD>';

grant all on <TE_MANAGEMENT_DB_NAME>.* to '<TE_MANAGEMENT_DB_USER>'@'<TE_DBSERVER>' IDENTIFIED BY '<TE_MANAGEMENT_DB_PASSWORD>';
grant SHOW DATABASES on *.* to '<TE_MANAGEMENT_DB_USER>'@'<TE_DBSERVER>';
grant FILE on *.* to '<TE_MANAGEMENT_DB_USER>'@'<TE_DBSERVER>';
grant CREATE USER on *.* to '<TE_MANAGEMENT_DB_USER>'@'<TE_DBSERVER>';
grant all on *.* to '<TE_MANAGEMENT_DB_USER>'@'<TE_DBSERVER>' IDENTIFIED BY '<TE_MANAGEMENT_DB_PASSWORD>';
grant GRANT OPTION on *.* to '<TE_MANAGEMENT_DB_USER>'@'<TE_DBSERVER>' IDENTIFIED BY '<TE_MANAGEMENT_DB_PASSWORD>';


grant all on <TE_MANAGEMENT_DB_NAME>.* to '<TE_MANAGEMENT_DB_USER>'@'<TE_DBSERVER_4MYSQL>' IDENTIFIED BY '<TE_MANAGEMENT_DB_PASSWORD>';
grant SHOW DATABASES on *.* to '<TE_MANAGEMENT_DB_USER>'@'<TE_DBSERVER_4MYSQL>';
grant FILE on *.* to '<TE_MANAGEMENT_DB_USER>'@'<TE_DBSERVER_4MYSQL>';
grant CREATE USER on *.* to '<TE_MANAGEMENT_DB_USER>'@'<TE_DBSERVER_4MYSQL>';
grant GRANT OPTION on *.* to '<TE_MANAGEMENT_DB_USER>'@'<TE_DBSERVER_4MYSQL>' IDENTIFIED BY '<TE_MANAGEMENT_DB_PASSWORD>';
grant all on *.* to '<TE_MANAGEMENT_DB_USER>'@'<TE_DBSERVER_4MYSQL>' IDENTIFIED BY '<TE_MANAGEMENT_DB_PASSWORD>';

grant all on <TE_MANAGEMENT_DB_NAME>.* to '<TE_MANAGEMENT_DB_USER>'@'<TE_WEBSERVER>' IDENTIFIED BY '<TE_MANAGEMENT_DB_PASSWORD>';
grant all on *.* to '<TE_MANAGEMENT_DB_USER>'@'<TE_WEBSERVER>' IDENTIFIED BY '<TE_MANAGEMENT_DB_PASSWORD>';
