  topicexplorer-db:
    #image: mariadb:10.11 => added multiuser_configuration via Dockerfile
    build:
      context: db
      dockerfile: Docker_mariadb   
    init: true 
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=<DB_ROOT_PW>
    volumes:
      - <DB_VOLUME_PATH>/mariadb-data:/var/lib/mysql
      - <DB_VOLUME_PATH>/logs:/var/log/mysql
      - <DB_VOLUME_PATH>/config:/etc/mysql/conf.d
    ports:
      - 3306

  adminer:
    image: adminer:4.8.1-standalone
    command: php -S 0.0.0.0:8080 -t /var/www/html
    restart: always
    depends_on:
      - topicexplorer-db
    environment:
      - ADMINER_PLUGINS=frames
    ports:
      - 8080

  waf:
    image: owasp/modsecurity-crs:nginx-alpine
    restart: always
    #environment:
    #  - BACKEND=http://nginx:80
    volumes:
      - <NGINX_VOLUME_PATH>/config/:/etc/nginx/templates/conf.d/
      - <NGINX_VOLUME_PATH>/pw/:/etc/nginx/pw/
      - <NGINX_VOLUME_PATH>/certs/:/etc/certs/
      - <NGINX_VOLUME_PATH>/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
    depends_on:
      <PROXY_DEP>
      - adminer
    ports:
      - <SERVERPORT>:80
      - 443:443
      

  phpmyadmin:
    image: phpmyadmin:5.2
    restart: always
    depends_on:
      - topicexplorer-db
    environment:
      - PMA_ABSOLUTE_URI=<HOST_URI>/pma
      - PMA_HOST=topicexplorer-db   
      - UPLOAD_LIMIT=250M
    ports:
      - 80